"""
Integration tests for end-to-end Ono functionality.
"""

import pytest
import tempfile
import os
from pathlib import Path


class TestEndToEndBasic:
    """Basic end-to-end tests."""

    def test_simple_template_conversion(self):
        """Test simple template conversion."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            output_file = Path(tmpdir) / "output.bash"
            
            input_file.write_text('?ono get temp directory ?')
            
            assert input_file.exists()

    def test_multiple_blocks_file(self):
        """Test file with multiple Ono blocks."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            
            content = '''# Script generated by Ono
x = "?ono first block ?"
y = "?ono second block ?"
# End of script
'''
            
            input_file.write_text(content)
            
            assert input_file.exists()
            assert '?ono' in content

    def test_nested_blocks(self):
        """Test file with nested Ono blocks."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            
            content = '?ono outer {?ono inner ?} ?'
            
            input_file.write_text(content)
            
            assert input_file.exists()


class TestFormatIntegration:
    """Format-specific integration tests."""

    def test_bash_output_format(self):
        """Test conversion to bash format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            output_file = Path(tmpdir) / "output.bash"
            
            content = '#!/bin/bash\n?ono get system info ?'
            input_file.write_text(content)
            
            assert input_file.exists()

    def test_python_output_format(self):
        """Test conversion to python format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            output_file = Path(tmpdir) / "output.py"
            
            content = '#!/usr/bin/env python3\n?ono get data ?'
            input_file.write_text(content)
            
            assert input_file.exists()


class TestMetadataGeneration:
    """Test metadata generation."""

    def test_inline_metadata(self):
        """Test inline metadata generation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            
            content = '''<?ono
@metadata inline
model=qwen3:1.7b
get data
?>
'''
            
            input_file.write_text(content)
            
            assert '@metadata' in content

    def test_file_metadata(self):
        """Test file-based metadata generation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            input_file = Path(tmpdir) / "test.ono"
            
            content = '''<?ono
@metadata file
 model=qwen3:1.7b
get data
?>
'''
            
            input_file.write_text(content)
            
            assert '@metadata' in content
