"""
Integration tests for Ono.
"""

import pytest
import tempfile
import os
from pathlib import Path
from ono import OnoParser


class TestFormatConversion:
    def setup_method(self):
        self.parser = OnoParser()
        self.temp_dir = tempfile.mkdtemp()

    def teardown_method(self):
        import shutil
        shutil.rmtree(self.temp_dir)

    def test_bash_output_format(self):
        """Test conversion to bash format."""
        text = '?ono pwd ?'
        result = self.parser.parse(text)
        rendered = self.parser.render(result)
        assert 'pwd' in rendered

    def test_python_output_format(self):
        """Test conversion to python format."""
        text = '?ono import os ?'
        result = self.parser.parse(text)
        rendered = self.parser.render(result)
        assert 'import os' in rendered

    def test_json_output_format(self):
        """Test conversion to JSON format."""
        text = '?ono {"key": "value"} ?'
        result = self.parser.parse(text)
        rendered = self.parser.render(result)
        assert '"key"' in rendered

    def test_text_output_format(self):
        """Test conversion to plain text."""
        text = '?ono hello world ?'
        result = self.parser.parse(text)
        rendered = self.parser.render(result)
        assert 'hello world' in rendered


class TestFileProcessing:
    def setup_method(self):
        self.parser = OnoParser()
        self.temp_dir = tempfile.mkdtemp()

    def teardown_method(self):
        import shutil
        shutil.rmtree(self.temp_dir)

    def test_simple_template_conversion(self):
        """Test simple template conversion."""
        input_file = Path(self.temp_dir) / "test.ono"
        input_file.write_text('?ono get temp directory ?')
        
        assert input_file.exists()

    def test_multiple_blocks_file(self):
        """Test file with multiple Ono blocks."""
        input_file = Path(self.temp_dir) / "test.ono"
        
        content = '''# Script generated by Ono
x = "?ono first block ?"
y = "?ono second block ?"
# End of script
'''
        
        input_file.write_text(content)
        
        assert input_file.exists()
        assert '?ono' in content

    def test_nested_blocks(self):
        """Test file with nested Ono blocks."""
        input_file = Path(self.temp_dir) / "test.ono"
        
        content = '?ono outer {?ono inner ?} ?'
        
        input_file.write_text(content)
        
        assert input_file.exists()

